### Site info.
title: Wayne.Sun's Blog
tagline: Java Programmer, Writer
author: Wayne Sun
email: sunswayne@gmail.com 
description: Wayne Sun, a lonely writer.
keywords: "Coding"
url: "http://waynesun.xyz" # The base hostname & protocol for your site
#url: "https://sunswayne.com" # The base hostname & protocol for your site
#enforce_ssl: "sunswayne.com" # The base hostname & protocol for your site
locale: en_US
encoding: UTF-8

### Personal info and site tools info.
twitter_username: sunswayne
github_username:  sunswayne
disqus_shortname: sunswayne
favicon:     "/images/favicon.ico"
aboutme: Wayne Sun, A man always chasing freedom.
aboutme_photo: "/images/1.png"
google_analytics_key: UA-57297247-1

### Site settings.
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True.
default_column: "two" # Blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # Blog sidebar language set, only include: English(en) and Chinese (cn).
path: "/_data/comments" # Path which stored comments etc.

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Google_Search: "Google Search"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
      WechatDBTalk: "Official WeChat"
      WechatDonate: "Donate"
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "Blogroll"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Google_Search: "搜索"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "
      WechatDBTalk: "微信公众号"
      WechatDonate: "微信捐赠"


### Blogroll info, only name can shown on the page.
Blogroll:
    - name: ImportNew
      href: http://www.importnew.com/
      title: ImportNew
    - name: 阮一峰的网络日志
      href: http://www.ruanyifeng.com/
      title: 阮一峰的网络日志
    - name: 酷壳
      href: http://coolshell.cn/
      title: 酷壳
    - name: MacTalk
      href: http://macshuo.com
      title: MacTalk
    - name: 并发编程网
      href: http://ifeve.com/
      title: 并发编程网

### Build settings.
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge
paginate: 5
excerpt_separator: <!--more-->

### Kramdown settings.
kramdown:
  input: GFM 
  hard_wrap: true
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
  syntax_highlighter: rouge

### Custom gems.
